services:
  mainnet_monero-wallet-rpc:
    container_name: mainnet_monero-wallet-rpc
    image: ghcr.io/sethforprivacy/simple-monero-wallet-rpc:v0.18.3.4
    restart: unless-stopped
    user: root
    volumes:
      - 'mainnet_monero-wallet-rpc-data:/monero-wallet-rpc-data/'
    expose:
      - ${MONERO_WALLET_RPC_PORT:?}
    entrypoint: ''
    command:
      - monero-wallet-rpc
      - '--rpc-bind-ip=0.0.0.0'
      - '--rpc-bind-port=${MONERO_WALLET_RPC_PORT:?}'
      - '--confirm-external-bind'
      - '--daemon-address=xmr-node.cakewallet.com:18081'
      - '--wallet-dir=/monero-wallet-rpc-data/'
      - '--disable-rpc-login'
      - '--trusted-daemon'
    # healthcheck:
    #   test: ["CMD", "nc", "-z", "localhost", "${MONERO_WALLET_RPC_PORT}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 20s
 
  mainnet_asb:
    image: ghcr.io/unstoppableswap/asb:latest
    restart: unless-stopped
    container_name: mainnet_asb
    depends_on:
      - mainnet_monero-wallet-rpc
        # condition: service_healthy
    volumes:
      - './config_mainnet.toml:/asb-data/config_mainnet.toml'
      - 'mainnet_asb-data:/asb-data'
    ports:
      - '0.0.0.0:${ASB_PORT:?}:${ASB_PORT:?}'
    entrypoint: ''
    command:
      - 'asb'
      - '--json'
      - '--config=/asb-data/config_mainnet.toml'
      - 'start'
volumes:
  mainnet_monero-wallet-rpc-data:
  mainnet_asb-data:
