[data]
dir = "/asb-data/"

[network]
listen = ["/ip4/0.0.0.0/tcp/9839", "/ip4/0.0.0.0/tcp/9840/ws"]
external_addresses = []
rendezvous_point = ["/dns4/discover.unstoppableswap.net/tcp/8888/p2p/12D3KooWA6cnqJpVnreBVnoro8midDL9Lpzmg8oJPoAGi7YYaamE", "/dns4/eratosthen.es/tcp/7798/p2p/12D3KooWAh7EXXa2ZyegzLGdjvj1W4G3EXrTGrf6trraoT1MEobs"]

[bitcoin]
electrum_rpc_url = "tcp://testnet_electrs:60001"
target_block = 1
network = "Testnet"

[monero]
wallet_rpc_url = "http://stagenet_monero-wallet-rpc:38083/json_rpc"
network = "Stagenet"

[tor]
control_port = 9051
socks5_port = 9050

[maker]
min_buy_btc = 0.0004
max_buy_btc = 0.15
ask_spread = 0.00
price_ticker_ws_url = "wss://ws.kraken.com/"
